### ISSUE TITLE
Enabling MVEBU_PCIE_ECAM_WA for ECAM workaround causes hang

### ISSUE THREAD

**Issue by b-man** [MarvellEmbeddedProcessors/uefi-marvell#1]
Hello,

I've gotten around to trying the new MVEBU_PCIE_ECAM_WA option
that enables use of the memory window hack to fix the ECAM bug, but
I've found that when this option is enabled my MACCHIATOBin hangs
at `ramdisk:blckio install. Status=Success`: 

>FS0:\> reset
>
> BootROM - 2.03
> Starting CP-1 IOROM 1.07
> Booting from SPI NOR flash 1 (0x32)
> Found valid image at boot postion 0x000
> lNOTICE:  Starting binary extension
> NOTICE:  SVC: SW Revision 0x0. SVC is not supported
> mv_ddr: mv_ddr-armada-18.09.2-g99d7725-dirty (Nov 04 2018 - 08:58:59 PM)
> mv_ddr: completed successfully
> NOTICE:  Cold boot
> NOTICE:  Booting Trusted Firmware
> NOTICE:  BL1: v1.5(release):711ecd32 (Marvell-armada-18.09.4)
> NOTICE:  BL1: Built : 20:59:03, Nov  4 2018
> NOTICE:  BL1: Booting BL2
> NOTICE:  BL2: v1.5(release):711ecd32 (Marvell-armada-18.09.4)
> NOTICE:  BL2: Built : 20:59:05, Nov  4 2018
> BL2: Initiating SCP_BL2 transfer to SCP
> NOTICE:  SCP_BL2 contains 2 concatenated images
> NOTICE:  Load image to CP1 MSS AP0
> NOTICE:  Loading MSS image from addr. 0x4023020 Size 0x135c to MSS at 0xf4280000
> NOTICE:  Done
> NOTICE:  Load image to AP0 MSS
> NOTICE:  Loading MSS image from addr. 0x402437c Size 0x1f6c to MSS at 0xf0580000
> N
> 
> FreeRTOS 7.3.0 - Marvell cm3 - A8K release armada-18.05.1
> 
> OTICE:  Done
> NOTICE:  SCP Image doesn't contain PM firmware
> NOTICE:  BL1: Booting BL31
> lNOTICE:  MSS PM is not supported in this build
> NOTICE:  BL31: v1.5(release):711ecd32 (Marvell-armada-18.09.4)
> NOTICE:  BL31: Built : 20:59:07, Nov  4 2018
> 
> Armada 8040 MachiatoBin Platform Init
> 
> Comphy0-0: PCIE0         5 Gbps
> Comphy0-1: PCIE0         5 Gbps
> Comphy0-2: PCIE0         5 Gbps
> Comphy0-3: PCIE0         5 Gbps
> Comphy0-4: SFI           10.31 Gbps
> Comphy0-5: SATA1         5 Gbps
> 
> Comphy1-0: SGMII1        1.25 Gbps
> Comphy1-1: SATA2         5 Gbps
> Comphy1-2: USB3_HOST0    5 Gbps
> Comphy1-3: SATA3         5 Gbps
> Comphy1-4: SFI           10.31 Gbps
> Comphy1-5: SGMII2        3.125 Gbps
> 
> UTMI PHY 0 initialized to USB Host0
> UTMI PHY 1 initialized to USB Host1
> UTMI PHY 2 initialized to USB Host0
> Succesfully installed protocol interfaces
> Detected w25q32bv SPI NOR flash with page size 256 B, erase size 4 KB, total 4 MB
> ramdisk:blckio install. Status=Success

Is there something that I'm missing?

**Comment by wojtas-marcin** [comment]
Hi @b-man 

Sorry for the late response. Without MVEBU_PCIE_ECAM_WA flag, 18.09 UEFI is capable of working in ECAM mode, however limited to the single device (bus0/device0). Due to the HW limitation multiple-devices PCIE (such as switches) usage is not possible by default in this mode with generic ECAM accessors. Anyway the flag requires also a ATF part, which is not published -such solution unfortunately is not 100% generic, so the customers should contact Marvell directly.

What kind of device is plugged to your MacchiatoBin? I built 18.09 with ths flag (without ATF part), and didn't observe the hang (the PCIE NIC I used was simply enumerated twice with the generic ECAM accessors, which is an actual problem to be worked-around).

Best regards,
Marcin

**Comment by b-man** [comment]
Marcin,

I've been using an Asus Radeon R7 240 graphics card, and more recently an Asus Geforce GT 710 graphics card. One thing that I've found with these cards is that the video and audio parts of the card
are enumerated as two distinct devices on bus0, which according to what you're describing likely explains why my board hangs when this workaround is enabled.

-- Brian

**Comment by wojtas-marcin** [comment]
@b-man Well, I've been using GT710 and it worked. It has a graphic and audio output on two functions of the bus0/device0, so I don't understand the crash you observe. I'll plug this device back and retry.

**Comment by b-man** [comment]
@semihalf-wojtas-marcin Did it work for you?
